/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaCafeteria;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Langas
 */
public class Proveedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_ID_Proveedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Nombre_Proveedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Direccion_Proveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Telefono_Proveedor = new javax.swing.JTextField();
        jButton_Registrar = new javax.swing.JButton();
        jButton_Modificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        label_status = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Buscar = new javax.swing.JTextField();
        jButton_Buscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID Proveedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txt_ID_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ID_ProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ID_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));

        jLabel2.setText("Nombre Proveedor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        getContentPane().add(txt_Nombre_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, -1));

        jLabel3.setText("Direccion Proveedor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        getContentPane().add(txt_Direccion_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, -1));

        jLabel4.setText("Telefono Proveedor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        getContentPane().add(txt_Telefono_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 90, -1));

        jButton_Registrar.setText("Registrar");
        jButton_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jButton_Modificar.setText("Modificar");
        jButton_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));
        getContentPane().add(label_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 160, 50));

        jLabel5.setText("Ingrese ID Proveedor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        getContentPane().add(txt_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 256, 80, -1));

        jButton_Buscar.setText("Buscar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 252, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ID_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ID_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ID_ProveedorActionPerformed

    private void jButton_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarActionPerformed
        // TODO add your handling code here:
        try{
            Connection cn = DriverManager.getConnection(Cafeteria.Base_de_Datos,Cafeteria.Usuario,Cafeteria.Clave);
            PreparedStatement pst = cn.prepareStatement("insert into Proveedores values(?,?,?,?)");

            pst.setString(1, txt_ID_Proveedor.getText().trim());
            pst.setString(2, txt_Nombre_Proveedor.getText().trim());
            pst.setString(3, txt_Direccion_Proveedor.getText().trim());
            pst.setString(4, txt_Telefono_Proveedor.getText().trim());
            pst.executeUpdate();

            txt_ID_Proveedor.setText("");
            txt_Nombre_Proveedor.setText("");
            txt_Direccion_Proveedor.setText("");
            txt_Telefono_Proveedor.setText("");
            label_status.setText("Registro exitoso.");
        }catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_RegistrarActionPerformed

    private void jButton_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarActionPerformed
        // TODO add your handling code here:
        try {
            String ID = txt_Buscar.getText().trim();

            Connection cn = DriverManager.getConnection(Cafeteria.Base_de_Datos,Cafeteria.Usuario,Cafeteria.Clave);
            PreparedStatement pst = cn.prepareStatement("update Proveedores set ID_Proveedor = ?,Nombre_Proveedor = ?, Direccion_Proveedor = ?,Telefono_Proveedor = ? where ID_Proveedor = " + ID);

            pst.setString(1, txt_ID_Proveedor.getText().trim());
            pst.setString(2, txt_Nombre_Proveedor.getText().trim());
            pst.setString(3, txt_Direccion_Proveedor.getText().trim());
            pst.setString(4, txt_Telefono_Proveedor.getText().trim());
            pst.executeUpdate();

            label_status.setText("Modificación exitosa.");

        } catch (Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_ModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = DriverManager.getConnection(Cafeteria.Base_de_Datos,Cafeteria.Usuario,Cafeteria.Clave);
            PreparedStatement pst = cn.prepareStatement("delete from Proveedores where ID_Proveedor = ?");

            pst.setString(1, txt_Buscar.getText().trim());
            pst.executeUpdate();

            txt_ID_Proveedor.setText("");
            txt_Nombre_Proveedor.setText("");
            txt_Direccion_Proveedor.setText("");
            txt_Telefono_Proveedor.setText("");
            txt_Buscar.setText("");

            label_status.setText("Registro eliminado.");

        } catch (Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        // TODO add your handling code here:
        try{
            Connection cn = DriverManager.getConnection(Cafeteria.Base_de_Datos,Cafeteria.Usuario,Cafeteria.Clave);
            PreparedStatement pst = cn.prepareStatement("select * from Proveedores where ID_Proveedor = ?");
            pst.setString(1, txt_Buscar.getText().trim());

            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                txt_ID_Proveedor.setText(rs.getString("ID_Proveedor"));
                txt_Nombre_Proveedor.setText(rs.getString("Nombre_Proveedor"));
                txt_Direccion_Proveedor.setText(rs.getString("Direccion_Proveedor"));
                txt_Telefono_Proveedor.setText(rs.getString("Telefono_Proveedor"));
            } else {
                JOptionPane.showMessageDialog(null, "Proveedor no registrado.");
            }

        }catch (Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton_BuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_Modificar;
    private javax.swing.JButton jButton_Registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label_status;
    private javax.swing.JTextField txt_Buscar;
    private javax.swing.JTextField txt_Direccion_Proveedor;
    private javax.swing.JTextField txt_ID_Proveedor;
    private javax.swing.JTextField txt_Nombre_Proveedor;
    private javax.swing.JTextField txt_Telefono_Proveedor;
    // End of variables declaration//GEN-END:variables
}
